### ISSUE TITLE
move_to need to handle nullptr trajectories

### ISSUE THREAD

**Issue by yepw** [ros-planning/moveit_task_constructor#105]
Hi, similar with a recent commit https://github.com/ros-planning/moveit_task_constructor/commit/6ff1a5162f99fb08dbf78311f0ebc0212d0b0506, move_to also need to handle nullptr trajectories:

https://github.com/ros-planning/moveit_task_constructor/blob/4225671ae4ecc6099376b41846d5fcc3adf1a173/core/src/stages/move_to.cpp#L234-L237

could be something like:
```ruby
double cost = 0;
if (robot_trajectory) {
	for (const double& distance : robot_trajectory->getWayPointDurations()) {
		cost += distance;
	}
}
```

**Comment by rhaschke** [comment]
You are right. I missed this one. Fixed now in master.
