### ISSUE TITLE
Demo fails for modular executable

### ISSUE THREAD

**Issue by cpt-yoshi** [ros-planning/moveit_task_constructor#113]
The **default** modular demo works. There are 2 _SerialContainer_ added to the _Task_. But when adding 8 _SerialContainer_ it fails:
```
Task createTask() {
	Task t;
	t.stages()->setName("Reusable Containers");
	t.add(std::make_unique<stages::CurrentState>("current"));

	const std::string group = "panda_arm";
	t.add(createModule(group));
	t.add(createModule(group));
	t.add(createModule(group));
	t.add(createModule(group));
	t.add(createModule(group));
	t.add(createModule(group));
	t.add(createModule(group));
	t.add(createModule(group));

	return t;
}
```
The planning works for the first 4 _SerialContainer_ but fails at _SerialContainer_ 5:

![rviz](https://user-images.githubusercontent.com/32679594/69298175-1c5fb880-0bdb-11ea-8b0f-cfd396c673b8.png)

**Comment by rhaschke** [comment]
The explanation is simple: Moving five times in a row to the left by 0.2m runs the robot into its limits. Thus the 5th attempt fails, which should be obvious from the visualization of the RobotState in rviz.

**Comment by cpt-yoshi** [comment]
At the end of each subtasks the robot returns to `moveTo ready` pose. Correct me if i'm wrong but shouldn't the robot be able to do this subtask any number of times because it returns to that pose after each subtask?

**Comment by rhaschke** [comment]
You are right. I missed that point. However, looking at the different solutions, you probably will observe that they are drifting into joint limits? This is because the arm is 7DoF and there is no mechanism to explicitly resolve the redundancy. I'm not sure though w/o looking into it.
