### ISSUE TITLE
 WARN : Computed trajectory is too short to detect jumps in joint-space

### ISSUE THREAD

**Issue by iamrajee** [ros-planning/moveit_task_constructor#126]
I'm trying to pick and place two objects one after another similar to what done here in the [demo](https://github.com/ros-planning/moveit_task_constructor/blob/master/demo/src/pick_place_task.cpp). I'm getting below warning while running the same. 
_**The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 7. Try a lower max_step.**_

Also, there is no successful planning solution is found for the "move to pick" stage for the second object. All other planning stage has successfully found the solution. You may see full code [here](https://github.com/iamrajee/ws_moveit/blob/master/src/moveit_task_constructor/demo/src/pick_place_task3.cpp).
I'm attaching a screenshot of warning and planning stages.
Any help will be highly appreciated.
![Screenshot from 2020-01-23 16-13-07](https://user-images.githubusercontent.com/25712145/72978919-43b24c00-3dfd-11ea-8b5f-ba43dbbef046.png)
![Screenshot from 2020-01-23 16-29-08](https://user-images.githubusercontent.com/25712145/72979084-925fe600-3dfd-11ea-9641-feb7419a69a6.png)
![Screenshot from 2020-01-23 16-29-22](https://user-images.githubusercontent.com/25712145/72979091-955ad680-3dfd-11ea-8a41-01ee6a6d6ef5.png)

**Comment by rhaschke** [comment]
The warning message is not an issue.
However, your sampling based planner cannot find a solution to connect from picked to place pose.
Inspect the messages on the console for details why the planners fail.

**Comment by iamrajee** [comment]
> The warning message is not an issue.
> However, your sampling based planner cannot find a solution to connect from picked to place pose.
> Inspect the messages on the console for details why the planners fail.

rosconsole did not provide any other information relevant to problem. Can you provide me with a simple example of how do we interface two containers/stage while performing a sequence of task e.g. doing pick and place task twice for different objects?

Thanks in advance!
**P.S.** - Stuck with this problem from long, couldn't move forward with it being solved.

**Comment by rhaschke** [comment]
The key question is how you initialize "generate grasp pose2".
While the _first_ grasp pose generator needs to be initialized from the _current state_:
https://github.com/ros-planning/moveit_task_constructor/blob/8588deb2020bf1016b2b30afd0594e83a0c939a8/demo/src/pick_place_task.cpp#L204

the _second_ grasp pose generator needs to be initialized from the _placed_ state, e.g. using the result of the "retreat after place" stage.

Note that you don't need to rename stages to have unique names.

**Comment by rhaschke** [comment]
The pick+place  demo automatically executes the best found plan:
https://github.com/ros-planning/moveit_task_constructor/blob/8588deb2020bf1016b2b30afd0594e83a0c939a8/demo/src/moveit_task_constructor_demo.cpp#L123

If you want to monitor this execution, you should indeed have a PlanningScene plugin instantiated in rviz. However, I don't like this automatic execution mode and thus would ask the users to modify their rviz setup to their likings.

**Comment by iamrajee** [comment]
> The key question is how you initialize "generate grasp pose2" ...

Thank you. I was able to solve the problem using the method suggested by you.

**Comment by corot** [comment]
Hey @iamrajee, would be nice if you can share your solution in the ROS answer. Will help other people with the same issue (like me)
Thanks!
