### ISSUE TITLE
demo->pickplace

### ISSUE THREAD

**Issue by Reaper151** [ros-planning/moveit_task_constructor#160]
@Reaper151 Common cause for IK failure is when the object is unreachable, but assuming this is not the case with you as you've already experimented with various object_pose. 
Although we have forbidden the collision between gripper and object before picking in the demo, it may so happen that some other part of the robot could be in collision with it while picking thus resulting in IK failure. You can increase the distance between gripper and object while picking by changing `grasp_frame_transform` in config file. e.g for panda arm you can do something like
```
grasp_frame_transform: [0, 0, 0.2, 1.571, 0.785, 1.571] #here 0.2 is that distance
```
Of course for your robot this could be different. If the problem still persists then surely go ahead and open a new issue.

_Originally posted by @iamrajee in https://github.com/ros-planning/moveit_task_constructor/issues/158#issuecomment-612975820_

I do what you suggest but still can't find solution for IK and this is sample of my object pose.

Edited: I realized that in panda it has 2 fake controllers for arm and hand but mine has only one. Is this the possible cause? -> This doesn't cause the problem because I created 2 fake controllers as demo but nothing change.

**Comment by v4hn** [comment]
Let's stay in the old thread for this.
