### ISSUE TITLE
[ERROR] Initialization failed: Error initializing stage: open hand: Unknown joint pose: open

### ISSUE THREAD

**Issue by Privilger** [ros-planning/moveit_task_constructor#177]
Hi, 
I'm using this package to do pick and place for my fetch robot. 
I change the `/demo/config/panda_config.yaml` a little bit.

It seems that I need to predefine some poses and name them, like `"open"`,  right?

If so, where can I define them?

Thanks

**Comment by rhaschke** [comment]
These predefined poses come from your robot's SRDF. You can edit them, for example, with the moveit setup assistant.

**Comment by Privilger** [comment]
Hi Robert,

The URDF file of the fetch robot is provided by the Fetch company. 
What should I do to add these predefined poses, can you give me some hints?

Thank you very much!

**Comment by rhaschke** [comment]
I talked about SRDF not URDF. The SRDF file is part of your moveit_config package for your robot. Please have a look into the [corresponding tutorial](http://docs.ros.org/melodic/api/moveit_tutorials/html/doc/setup_assistant/setup_assistant_tutorial.html) for details.

**Comment by Privilger** [comment]
Thanks a lot!
