### ISSUE TITLE
move real robot

### ISSUE THREAD

**Issue by Privilger** [ros-planning/moveit_task_constructor#178]
Hi,

I'm testing a small case that closes the fetch robot's gripper.

I follow the panda robot demo, adding a yaml file, and add a group_state in the srdf file.

I can see the animation in Rviz that the gripper is closing. But the real robot does not move its gripper. 

The rqt_graph looks not correct.
![mtc_problem](https://user-images.githubusercontent.com/16457013/84665514-81ea0c80-af52-11ea-87c1-9f48a833351f.png)

Is there someplace I  miss configuring?

**Comment by v4hn** [comment]
I have no idea how you ended up with that graph. `execute_task_solution` should be an action provided by the `move_group` node, whereas it is advertised by `/mtc_tutorial_fetch` in your case.

It looks like there is no communication with any kind of robot controller (controlling the gripper).
So this is not an MTC issue, but a basic issue in your setup.
