### ISSUE TITLE
How to programatically add a group_state

### ISSUE THREAD

**Issue by Privilger** [ros-planning/moveit_task_constructor#179]
Hi,

According to the demo, it seems that we need to predefine a lot of `group_state` in srdf file.

It can be inconvenient since sometimes we even don't know what the `named_pose` should be when the robot is grasping(don't know how much the gripper should open). 

Is it possible to combine with the MoveIt API `void moveit::planning_interface::MoveGroup::rememberJointValues` or something else that allows us to set while running?

**Comment by v4hn** [comment]
This has nothing to do with MTC, but is about MoveIt's capabilities to store states (which are basically maps from joint names to values).
You don't have to use named poses anywhere in MTC, it's just convenient if you only have a few states.

You can manage your states yourself (nothing wrong with a simple map of maps) or rely on the https://github.com/ros-planning/warehouse_ros as a database (it's not as straight-forward to use that as it might look).
