### ISSUE TITLE
Handle Property exceptions provide useful hints

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit_task_constructor#18]
If we have a complex hierarchy of nested stages as the `Pick` container, propagating properties from the top-level down to the actual compute stages is a nightmare. First a capability is needed, that analyzes catched property exceptions (of different types, see below) and provides more useful hints how to resolve the issue.
The exception is usually thrown by the `Property` class. The (usually) calling `PropertyMap` class, could catch the exception, use a to-be-provided method to analyse the error and finally rethrow the exception, but with a more useful error message. The outer context could catch the exception again (placing `compute()` into a try-catch-block), perform more analyses, print some error messages and/or rethrow with extended message and so on.

- [x] Introduce different exception types, all deriving from Property::exception:
  - [x] undeclared
  - [x] undefined
  - [x] type_error
- [x] Utility method in `PropertyMap` to analyze the error.
  Is the property expected to be inherited from some source, but not provided?
- [x] introduce a try-catch-block in `Stage(Private)::compute()` and continue analysis using the parent's `PropertyMap`.
- [x] For containers, provide a mechanism to expose a set of properties of specific children. Currently it's necessary to first declare all these properties (again), and second to declare them (in the child's `PropertyMap`) for inheritance from parent. This should be handled by a convience function in `ContainerBase`, e.g. `exposeProperties(child, {property names})`.

**Comment by v4hn** [comment]
I believe this is closed for now.
We will probably add more debugging output as we move along implementing pipelines.
