### ISSUE TITLE
Preempted ExecuteTaskSolution action server won't execute new goal 

### ISSUE THREAD

**Issue by YannickRiou** [ros-planning/moveit_task_constructor#217]
When trying to cancel a goal sent to ExecuteTaskSolution action server, the goal is cancelled and the robot movement is stopped but if I try to execute another goal, the action server won't execute the goal and stay in a PREEMPTED state. 

Here the routine showing the problem that I'm facing. The routine is called in a callback function : 
**First call of the callback :** 
- Create an ExecuteTaskSolution action client, tell to execute a task that was previously planned
- Call the cancelGoal function with the action client.
- Goal is cancelled, task execution is stopped and action server is now in "aborted" state

**Second call of the callback :** 
- Create an ExecuteTaskSolution action client,  tell to execute a task that was previously planned
- Task doesn't execute and ExecuteTaskSolution action client immediatly finished with PREEMPTED.

If needed I will try to come up with a minimal example.

My investigation : 

The moveit function "executeAndMonitor" (moveit_ros/planning/plan_execution/src/plan_execution.cpp) called in the goalCallback of the execute_task_solution_capability is still having the preempt_requested_ variable set to true. 
This variable is only set to false in the PlanExecution constructor or in the planAndExecute function that aren't used in the ExecuteTaskSolution capability (tell me if I'm wrong).

It seems to be mainly of Moveit problem but I thought this can also be how MTC send a preempt signal to moveit. 
My quick and dirty fix : add preempt_requested_ = false at https://github.com/ros-planning/moveit/blob/9f9e69c54529e1aa156851abb6aae7047b20780d/moveit_ros/planning/plan_execution/src/plan_execution.cpp#L423 . It works (I am able to execute new goal after a cancelled one) but I don't think it is the proper way to do it.

**Comment by rhaschke** [comment]
I confirm this issue. Thanks for pointing at a possible solution! I filed a corresponding PR: https://github.com/ros-planning/moveit/pull/2403
