### ISSUE TITLE
Motion Planning Tasks Rviz plugin is keeping old tasks

### ISSUE THREAD

**Issue by MarqRazz** [ros-planning/moveit_task_constructor#224]
I am seeing an issue where the Rviz plugin is holding onto all plans since startup. This can make for a very large "Task Tree" and after a new task is received the old ones are no longer valid so you can't see any of the solutions.
![image](https://user-images.githubusercontent.com/25058794/103017963-a88c8f80-4501-11eb-9420-e9da0519d264.png)

**Comment by rhaschke** [comment]
This is on purpose: it allows you to inspect _received_ solutions even though the corresponding mtc node already finished.
However, you are right, this is limited to actually published solutions (typically top-level ones).
In the master branch you are able to customize how the plugin will handle new incoming tasks that override existing old ones:
You can choose between keep (all), replace existing, and always remove. Just go into the settings tab:

![image](https://user-images.githubusercontent.com/5376030/103018939-4efa8400-4546-11eb-8e7f-671f98427f04.png)

**Comment by MarqRazz** [comment]
I figured there would be an option for this. Thanks for pointing me to the settings!!
