### ISSUE TITLE
Fallback Stage Segfault

### ISSUE THREAD

**Issue by danem** [ros-planning/moveit_task_constructor#234]
When using the Fallback container I am getting a segfault at [this line](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/src/container.cpp#L695). It appears the `active_child_` pointer gets corrupted at some point.

[Here](https://gist.github.com/danem/e85ccb396303f6b76cc7e07d6857d554) is a test to reproduce the error.

Note that I only see the segfault when all of the children of the fallback container fail.

**Comment by rhaschke** [comment]
Thanks for reporting. There was a nasty bug in there: If all children stages of a fallback container failed, the `active_child_` pointer was dangling. Fix on master.
