### ISSUE TITLE
Q: Planning fails without any debug information

### ISSUE THREAD

**Issue by dnandha** [ros-planning/moveit_task_constructor#236]
This is a general question on how to debug the planning stages in mtc:

I'm using a robot configuration different from Panda and even a simple planning task such as moving in Z by -0.2 fails (the robot configuration works fine in the moveit planning interface). No exception is thrown and no debug information is printed, only the return value of `.plan()` is False. Is there any way how I could debug the situation?

**Comment by rhaschke** [comment]
The suggested method to debug is to inspect the plan in rviz. As long as you keep the MTC ROS node alive, you can inspect all stages visually in rviz. Did you try this?

**Comment by v4hn** [comment]
Closed by timeout. Feel free to write again if you have further questions.
