### ISSUE TITLE
Migration from Travis to Github actions

### ISSUE THREAD

**Issue by JafarAbdi** [ros-planning/moveit_task_constructor#260]
Are you planning to migrate this repo to use GitHub actions rather than Travis .? If yes I can open PR to do that

**Comment by rhaschke** [comment]
Yes, I want to migrate to GHA here as well. I want to use the set of configs I adopted for rviz...

**Comment by v4hn** [comment]
> Yes, I want to migrate to GHA here as well. I want to use the set of configs I adopted for rviz...

Is there a big difference between rviz and moveit's configuration?
I would prefer to streamline with MoveIt's other repositories instead.
But yes, I'm basically waiting for someone (Robert, Tyler or you) to provide the patches as all of you work with these CI setups way more than I do.
