### ISSUE TITLE
Initial states does not match the current state 

### ISSUE THREAD

**Issue by stevedanomodolor** [ros-planning/moveit_task_constructor#263]
MY setup 
Ubuntu 20 
ros-noetic 
Default planner is ompl 
I currenlty adapted the ur10 to with the cartesian example in the moveit task tutorial but the issue is that the initial state does not match the initial scene of the robot. It keeps taking the zeros pose and the home_pose i set as initial pose. 
![image](https://user-images.githubusercontent.com/61468301/116960761-aa314580-aca1-11eb-96cf-79775cc971f5.png)

**Comment by rhaschke** [comment]
As stated in the source comment, the cartesian.cpp example starts from a _fixed_ robot state:
https://github.com/ros-planning/moveit_task_constructor/blob/ba0b4f61460612a9c1a3e037ac14f316c5e84223/demo/src/cartesian.cpp#L61-L71

If you want to start from the current scene state, you should use the `CurrentState` stage instead:
https://github.com/ros-planning/moveit_task_constructor/blob/ba0b4f61460612a9c1a3e037ac14f316c5e84223/demo/src/pick_place_task.cpp#L122
