### ISSUE TITLE
Motion Planning tasks introspection is wrong when using map as fixed frame

### ISSUE THREAD

**Issue by YannickRiou** [ros-planning/moveit_task_constructor#291]
Hi,

There seems to be a problem when trying to review the planned task stages on robot that is localized into a map. 

![problem_mtc_map](https://user-images.githubusercontent.com/59170639/133256028-0a342692-f3d0-48e7-a108-75287e565711.png)

As you can see on the above picture, I want to review the "grasp pose IK" stage, when  I click on it, another robot with it's environment appears at the origin of the map (in the foreground of the above picture). 
The actual robot position is at the background of the above picture.

It seems also to affects the view of the poses generated by moveit task constructor. 

The expected behavior is that the stage review should show the robot at it's actual localized position

Here is what happen in a video, when I want to review the solution found, another robot appear at the origin of the map instead of the actual position of the robot : 

https://user-images.githubusercontent.com/59170639/133257627-2aeeab73-32ec-45bd-9857-499ff894a21b.mp4

Feel free to ask if something is unclear.

**Comment by v4hn** [comment]
Could you try to provide a minimal example?
Do you see similar problems with other robot links, or is this only a problem with your map frame?
Does your moveit config specify a planar/floating virtual joint?

**Comment by rhaschke** [comment]
I am able to reproduce the issue. It's a bug in MoveIt's PlanningSceneDisplay actually. I will file a PR.
