### ISSUE TITLE
Missing task name setting in task constructor

### ISSUE THREAD

**Issue by YannickRiou** [ros-planning/moveit_task_constructor#300]
A part of code is missing in the task constructor in task.cpp 

Earlier it was set like this : 
 ```
Task::Task(const std::string& id, bool introspection, ContainerBase::pointer&& container)
  : WrapperBase(new TaskPrivate(this, id), std::move(container)) {
	if (!id.empty())
		stages()->setName(id);

	// monitor state on commandline
	// addTaskCallback(std::bind(&Task::printState, this, std::ref(std::cout)));
	// enable introspection by default, but only if ros::init() was called
	if (ros::isInitialized() && introspection)
		enableIntrospection(true);
}
 ```

But now if I'm not mistaken (and it's not being set elsewhere) it is missing. 
https://github.com/ros-planning/moveit_task_constructor/blob/55e30e26ce8396993d2af93156c92816659c6270/core/src/task.cpp#L110

It causes the task to be named "task pipeline", which is the default name of the high-level serial container of the task, even when giving a string in the constructor.

**Comment by JafarAbdi** [comment]
@YannickRiou I think  [setName](https://github.com/ros-planning/moveit_task_constructor/blob/55e30e26ce8396993d2af93156c92816659c6270/core/include/moveit/task_constructor/task.h#L83) is what you're looking for, right .?
