### ISSUE TITLE
MTC Build errors in ROS2

### ISSUE THREAD

**Issue by juiceine** [ros-planning/moveit_task_constructor#317]
Hi there,

I tried to install the Task Constructor for ROS2 Foxy. However, I stumble on build errors that seem related to the code itself. Is the ROS2 branch already ready for usage or is this still WIP? Any advice would be welcome!

System:
Ubuntu 20.04
ROS2 Foxy
MoveIt2 (binary install)

How to reproduce:
Install the Task Constructor according to the MoveIt 1 - Noetic tutorial, but replace 
`git clone https://github.com/ros-planning/moveit_task_constructor.git`
by
`git clone https://github.com/ros-planning/moveit_task_constructor.git -b ros2`

Expected result:
Building without problems

Actual result:
There occur some errors that seem to be related to the C++ files in moveit_task_constructor/core. I first get errors related to `setw`, but I could overcome those by adding `#include <iomanip>` to container.cpp. After that, I get multiple errors related to classes having no members. 

![setw_error](https://user-images.githubusercontent.com/54582035/144607129-31443c53-6d9e-4172-8523-3dc64dde865b.png)
![nomember_error](https://user-images.githubusercontent.com/54582035/144607141-6329b997-b464-4266-a2dd-d9921118750c.png)

**Comment by JafarAbdi** [comment]
Currently, the `ros2` branch doesn't work on `foxy` due to the difficulty of maintaining 3 distros in the same branch, I'll push a new branch with fixes for foxy, it should be ready in an hour

**Comment by sabinevanderwerff** [comment]
It has been a while, but I was wondering if there is any progress with this?
