### ISSUE TITLE
Crash when stage is a member variable

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit_task_constructor#325]
```
std::unique_ptr<moveit::task_constructor::stages::MoveTo> open_fingers_stage_;
...
open_fingers_stage_->setGroup(finger_group_);
open_fingers_stage_->setGoal(arm_prefix_ + "fingers_open");
task_.add(std::move(open_fingers_stage_));
...
try {
  task_.init();
  task_.enableIntrospection(true);
  RCLCPP_ERROR_STREAM(LOGGER, "Done enabling introspection");
} catch (InitStageException & e) {
  RCLCPP_ERROR_STREAM(LOGGER, "Initialization failed: " << e);
  return false;
}
```

Stack trace:

`[ERROR] [mtc_demo_node-1]: process has died [pid 30956, exit code -11, cmd '/opt/colcon_ws/install/bro_manipulation_manager/lib/bro_manipulation_manager/mtc_demo_node --ros-args --params-file /tmp/launch_params_hnsr2_j0 --params-file /tmp/launch_params_vr1h9ke9 --params-file /tmp/launch_params_u_eb_jru --params-file /tmp/launch_params_41h_88id --params-file /tmp/launch_params_k61na_z_'].`

This works fine if open_fingers_stage_ is a local variable, like:

```
    auto stage = std::make_unique<MoveTo>(
      PICK_STAGE_MAP.at(PickStageEnum::OPEN_FINGERS),
      sampling_planner);
    stage->setGroup(finger_group_);
    stage->setGoal(arm_prefix_ + "fingers_open");
    task_.add(std::move(stage));
```

**Comment by rhaschke** [comment]
I guess you try to access the member variable after moving it into the task?
Otherwise, I don't see a reason why this should fail.

**Comment by AndyZe** [comment]
Nope, I double checked. Here's a grep of `open_fingers_stage_` to verify:

```
src/MTC_manager.cpp:    open_fingers_stage_->setGroup(finger_group_);
src/MTC_manager.cpp:    open_fingers_stage_->setGoal(arm_prefix_ + "fingers_open");
src/MTC_manager.cpp:    task_.add(std::move(open_fingers_stage_));
include/bro_manipulation_manager/MTC_manager.hpp:  std::unique_ptr<moveit::task_constructor::stages::MoveTo> open_fingers_stage_;
```

**Comment by rhaschke** [comment]
Where is the initialization/creation of `open_fingers_stage_`? Did you cover all files?

**Comment by AndyZe** [comment]
Geez, you are right. Initialization was missing. Thanks
