### ISSUE TITLE
pickplace demo on Galactic

### ISSUE THREAD

**Issue by cs-99** [ros-planning/moveit_task_constructor#394]
While writing a component for picking and placing objects via the moveit task constructor i ran into an issue where the inverse kinematic would always fail due to what seems like an empty pose. I then checked the demo (via demo.launch.py and pickplace.launch.py as in the tutorial) to see that the same problem is occuring there.
![pickplacedemo](https://user-images.githubusercontent.com/67115649/202857623-166979d6-e0cd-459f-88a6-5721805d2564.png)
For context: I am running Ubuntu 20.04 LTS with ROS Galactic and used this repositories galactic branch.
Can anyone help me out? Thanks in advance.

**Comment by JafarAbdi** [comment]
Sounds similar to https://github.com/ros-planning/moveit2/pull/1274, can you make sure moveit version you use have those fixes?

**Comment by cs-99** [comment]
@JafarAbdi My moveit version does not include those fixes. Sadly i have not been able to get a version including them running, as building from source (using [this](https://moveit.ros.org/install-moveit2/source/)) with manually applied changes did not work for me. The build process gets terminated by the OS after completely filling up my RAM (16GB). Do you have any recommendations on how to install a suitable moveit version?
