### ISSUE TITLE
Can I know how to use MTC for Universal Robot 5e

### ISSUE THREAD

**Issue by adithyakumarcr** [ros-planning/moveit_task_constructor#434]
Hi Developers!

I am a beginner with Moveit packages. I would like to use MTC with UR5e. Can anyone help me with steps how I can follow to have it running on both Rviz (fake controllers) and Realrobot. I would like to do with Humble/moveit2. I tried the tutorials and it worked. Not sure, what I should I change in order to have it working for UR5e. 

Thanks.

**Comment by rhaschke** [comment]
Just replace the Panda robot of the tutorials with your UR5, i.e. change URDF description, link names, and controller names. That's the cool thing about abstract, high-level API: It works with a few changes on any robot.
