### ISSUE TITLE
setFromIK fails for ik_frame that is not fixed to the IK solver's eef

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit_task_constructor#440]
I'm using the tip of the finger while trying to `ComputeIK` for the robot arm, whose JMG doesn't include hand joints.
RobotState's `setFromIK` should consider the current configuration of the hand joints and compute some valid solution, shouldn't it?

**Comment by rhaschke** [comment]
Will be fixed via https://github.com/ros-planning/moveit/pull/3388

**Comment by v4hn** [comment]
Addressed after you merged the PR.

Thank you for this feature, I needed it as well in the past, but worked around it then.
