### ISSUE TITLE
Rosdep issues with galactic

### ISSUE THREAD

**Issue by orjano-max** [ros-planning/moveit_task_constructor#444]
### Issue
Cloned the galactic branch into my workspace src folder:
```bash
git clone https://github.com/ros-planning/moveit_task_constructor.git -b galactic
```
Ran rosdep:
```bash
rosdep install --from-path src --ignore-src -y --rosdistro galactic
```
Galactic was sourced ofc. and rosdep is set to include eol distros.
Got this error:
```bash
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
moveit_task_constructor_demo: Cannot locate rosdep definition for [rosparam_shortcuts]
```
### Solution
Cloning the source code into my directory worked:
```bash
git clone https://github.com/PickNikRobotics/rosparam_shortcuts -b ros2
```
I guess there are no binaries available of this package for galactic

**Comment by rhaschke** [comment]
> I guess there are no binaries available of this package for galactic

Exactly. That's why you need to build that package from source as well.
