### ISSUE TITLE
roslaunch file contains muitpile nodes,how to solve?

### ISSUE THREAD

**Issue by 23456789zs** [ros-planning/moveit_task_constructor#447]
RLException: roslaunch file contains multiple nodes named [/robot_state_publisher].
Please check all <node> 'name' attributes to make sure they are unique.
Also check that $(anon id) use different ids.
The traceback for the exception was written to the log file

How to solve this problem?Thanks very much

**Comment by rhaschke** [comment]
Do exactly what you are asked for: check your launch files for multiple occurrences of `/robot_state_publisher`.
