### ISSUE TITLE
Fallback Container

### ISSUE THREAD

**Issue by leander2189** [ros-planning/moveit_task_constructor#452]
I am trying to set the following behaviour using Fallback Container:

Fallback:
- Option A: Connect stage
- Option B: SerialContainer
    - MoveTo
    - Connect

But I get an exception stating that only Connect stages are allowed. Is there any design reason for this? Could I extend the functionality of this container to accept also a SerialContainer?

Any hint on how would be the best way to implement this mod is welcome.

**Comment by rhaschke** [comment]
The reason that Fallback containers are restricted to Connect stages is a very fundamental one: we need to know that all potential solutions a child could generate for a specific pair start-end states are _exhausted_. As we don't have that notion for containers (yet), we decided to limit Fallback containers to Connect stages, where a failure is equal to an exhaustive failure. However, contributions are generally highly appreciated. But we need to very carefully decide a new API for this...
See #311 for more details.
