### ISSUE TITLE
Specify effort for GripperCommand

### ISSUE THREAD

**Issue by TheUncivil** [ros-planning/moveit_task_constructor#479]
I am operating a gripper using a `GripperCommand` controller. For my application, I'd like to specify effort for the operation, as well as the position. Is there a way to achieve this using the MTC?

**Comment by rhaschke** [comment]
`JointInterpolationPlanner` provides a `max_effort` property that is passed to the controller:
https://github.com/ros-planning/moveit_task_constructor/commit/7f10292ab349da7f1c611d31ca38f4bf8dd16112
