### ISSUE TITLE
What happened to the humble branch?

### ISSUE THREAD

**Issue by lukas-jung** [ros-planning/moveit_task_constructor#480]
The humble branch disappeared at some point during the last week.
This causes some problems when following the getting started guide for moveit2(humble).

Is there a reason for that or was it just a mistake?

Thanks in advance!

**Comment by rhaschke** [comment]
There is (and was) no need for a separate `humble` branch. Simply use `ros2`. Please file a PR to fix the getting starting guide. Thanks.
