### ISSUE TITLE
build failure due to typos from converting to private variables

### ISSUE THREAD

**Issue by JHeuverRiwo** [ros-planning/moveit_task_constructor#482]
Hello,

I have encountered more than a few typos causing build errors. It seems they have originated from a switch to trailing underscores for some private variables. They happen in execute_task_solution_capability.cpp and pipeline_planner.cpp.

examples:

moveit_task_constructor/core/src/solvers/pipeline_planner.cpp:183:22: error: ‘struct planning_interface::MotionPlanResponse’ has no member named ‘trajectory’; did you mean ‘trajectory_’?
  183 |         result = res.trajectory;

this also goes for line 208 in pipeline_planner.cpp

**Comment by rhaschke** [comment]
You are probably using ROS Humble with the default MoveIt installation. For this use case there is a separate branch: [`humble`](https://github.com/ros-planning/moveit_task_constructor/tree/humble), which fixes those issues: 564804bd7bb9e320b304b8c4880d96c6ce63b915
