### ISSUE TITLE
Memory leak in RViz display

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit_task_constructor#50]
I currently see a huge memory leak in RViz when I plan and visualize a task with our display.
I didn't have a chance to look into it yet though and it might be a problem of my local ROS setup.

@rhaschke you fixed memory leaks in there before, do you still observe them here?

**Comment by rhaschke** [comment]
Could you please be more concrete?
Of course, the display caches the scenes and solutions of all submitted solutions.

Which kind of display options are you using?
This might be related to https://github.com/ros-visualization/rviz/issues/1222 if you have traces enabled.

Is memory freed when you remove tasks from the display?
Is the memory freed when removing the display?

**Comment by rhaschke** [comment]
Looks like PlanningScenes are never destructed. Maybe there is a circular reference of PlanningScenePtrs.
No classic leak that could be found with asan address sanitizer.

**Comment by rhaschke** [comment]
No, its not the PlanningScenes. They are nicely destroyed.
I now also see a continuous increase of memory when only a single solution is displayed...

**Comment by rhaschke** [comment]
However, this is plain rviz receiving tf messages (+1MB per ~15s). I think that's normal.

**Comment by rhaschke** [comment]
I have no more ideas for now. Definitely, the memory allocated by new display solutions is not freed, although the solutions themselves are.
@v4hn Please provide more insight from your side.

**Comment by rhaschke** [comment]
The underlying reason was rviz: https://github.com/ros-visualization/rviz/pull/1294.

**Comment by rhaschke** [comment]
I released rviz with the corresponding fix a while ago :wink:
