### ISSUE TITLE
Building MTC does not set up the Python wrapper module properly

### ISSUE THREAD

**Issue by cambel** [ros-planning/moveit_task_constructor#522]
I am trying to use MTC through the Python wrappers.

After successfully building from the source and trying to execute the demos from the tutorial, it cannot find the `moveit.task_constructor` Python module.

Checking the build log I found this warning:

```shell
Warnings   << moveit_task_constructor_core:symlink /root/ros_ws/logs/moveit_task_constructor_core/build.symlink.000.log
Warning: Cannot symlink from /root/ros_ws/devel/.private/moveit_task_constructor_core/lib/python3/dist-packages/moveit/__init__.py to existing file /root/ros_ws/devel/lib/python3/dist-packages/moveit/__init__.py
```

I tried "catkin clean && catkin build" but I still got the same issue.

This issue seems related to #520 

### Workaround
If I manually delete the existing file `.../moveit/__init__.py` and create the symbolic link, then I can find the `moveit.task_constructor` Python module. But I would need to do that every time I do a clean catkin build

**Comment by KejiaChen** [comment]
Hi cambel, I have the same issue. Could you please explain how you solved it?

**Comment by cambel** [comment]
Hi @KejiaChen 

In my case, I basically execute these two commands:
```shell
rm /PATH-TO-ROS-WORKSPACE/devel/lib/python3/dist-packages/moveit/__init__.py
ln -s /PATH-TO-ROS-WORKSPACE/devel/.private/moveit_task_constructor_core/lib/python3/dist-packages/moveit/__init__.py  /PATH-TO-ROS-WORKSPACE/devel/lib/python3/dist-packages/moveit/__init__.py
```

**Comment by rhaschke** [comment]
Try to an install build: `catkin config --install`. There are fundamental problems with the devel-space layout.

**Comment by cambel** [comment]
@rhaschke 

Thanks, that works for me.

Just to clarify, after building, do not forget to source from the `install` folder. For example:
```shell
source /PATH_TO_ROS_WORKSPACE/nit/setup.bash
```
