### ISSUE TITLE
Significant deviance in IK computation 

### ISSUE THREAD

**Issue by denizkitu** [ros-planning/moveit_task_constructor#526]
I've been trying to perform pick and place with MoveIt Task Constructor but the ik_frame and target_frame never seems to overlap as they should. I've made sure that the reference frame that ik solver uses is the gripper's frame. But i observed that none of the frames reach the target_frame.
![Screenshot from 2024-01-23 15-39-55](https://github.com/ros-planning/moveit_task_constructor/assets/119333956/ba6d1374-23e3-474b-b384-2ebd978fba54)
This is my code: (almost the same as in the panda example)
```
#! /usr/bin/env python

from moveit_commander.roscpp_initializer import roscpp_initialize
from moveit.task_constructor import core, stages
from moveit_commander import PlanningSceneInterface
from geometry_msgs.msg import PoseStamped, TwistStamped
import time

roscpp_initialize("pickplace")


arm = "arm_controller"
eef = "hand"

object_name = "grasp_object"
object_radius = 0.02

psi = PlanningSceneInterface(synchronous=True)
psi.remove_world_object()

objectPose = PoseStamped()
objectPose.header.frame_id = "world"
objectPose.pose.orientation.x = 1.0
objectPose.pose.position.x = 0.30702
objectPose.pose.position.y = 0.0
objectPose.pose.position.z = 0.285

psi.add_box(object_name, objectPose, size=[0.03, 0.03, 0.03])

task = core.Task("PandaPickPipelineExample")
task.enableIntrospection()

task.add(stages.CurrentState("current"))

pipeline = core.PipelinePlanner()
pipeline.planner = "RRTConnectkConfigDefault" 
planners = [(arm, pipeline)]


task.add(stages.Connect("connect", planners))

grasp_generator = stages.GenerateGraspPose("Generate Grasp Pose")
grasp_generator.angle_delta = 0.2
grasp_generator.pregrasp = "open"
grasp_generator.grasp = "close"
grasp_generator.setMonitoredStage(task["current"])  


simpleGrasp = stages.SimpleGrasp(grasp_generator, "Grasp")

ik_frame = PoseStamped()
ik_frame.header.frame_id = "gripper_link"
ik_frame.pose.position.z = 0.09 
ik_frame.pose.position.y = -0.02
simpleGrasp.setIKFrame(ik_frame)

pick = stages.Pick(simpleGrasp, "Pick")
pick.eef = eef
pick.object = object_name


approach = TwistStamped()
approach.header.frame_id = "world"
approach.twist.linear.z = -1

pick.setApproachMotion(approach, 0.04, 0.40)


lift = TwistStamped()
lift.header.frame_id = "gripper_link"
lift.twist.linear.z = -1.0
pick.setLiftMotion(lift, 0.03, 0.1)

task.add(pick)

if task.plan():
    task.publish(task.solutions[0])


del pipeline
del planners

time.sleep(3600)
```

**Comment by v4hn** [comment]
This looks like a bug in the IK solver setup you configured for the joint model group arm_controller, which returns this pose as a successful solution.

We could add another check to validate the solution through forward kinematics in the ComputeIK stage, but the solver is already expected to ensure that whatever it returns with `success == true` is actually successful.

**Comment by denizkitu** [comment]
> This looks like a bug in the IK solver setup you configured for the joint model group arm_controller, which returns this pose as a successful solution.
> 
> We could add another check to validate the solution through forward kinematics in the ComputeIK stage, but the solver is already expected to ensure that whatever it returns with `success == true` is actually successful.

I have two possible reasons as to why this is happening:

I've added this line at kinematics.yaml because ik solver couldn't find any solutions at all with error "no IK found"
`  position_only_ik: true`

Two: My robotic arm model has 5 degrees of freedom (except the gripper) instead of 6.

**Comment by v4hn** [comment]
both reasons are severe issues.

If you are restricted to 5dof in the arm you likely need to provide a custom grasp sampler that considers the reachable pose space of your arm.

**Comment by rhaschke** [comment]
I tested your example code. However, for me _all_ IK solutions fail:
```
        0  - ←   0 →   -  0 / compute ik
         32  - ←  32 →   - 32 / Generate Grasp Pose
```
Which IK solver do you use? It looks like the 5dof arm cannot reach any of the requested poses (exactly enough). But, I am also confused that ComputeIK doesn't show any failure markers. Needs further investigation.

**Comment by denizkitu** [comment]
> position_only_ik: true

Did you add this line to kinematics.yaml: `position_only_ik: true`
Also you have to use a 5 DoF robot model to reproduce the error.

**Comment by denizkitu** [comment]
> I tested your example code. However, for me _all_ IK solutions fail:
> 
> ```
>         0  - ←   0 →   -  0 / compute ik
>          32  - ←  32 →   - 32 / Generate Grasp Pose
> ```
> 
> Which IK solver do you use? It looks like the 5dof arm cannot reach any of the requested poses (exactly enough). But, I am also confused that ComputeIK doesn't show any failure markers. Needs further investigation.

Did you add this line to kinematics.yaml: `position_only_ik: true`
Also you have to use a 5 DoF robot model to reproduce the error. I use the KDL ik solver. I tried to install IKFast but i got tons of errors.

**Comment by rhaschke** [comment]
KDL is good, particularly for underactuated arms. You could even balance orientation vs. position error. For further investigation, please prepare a zip comprising all relevant packages (URDF, SRDF/moveit_config, your source, exact commands to reproduce.)

**Comment by denizkitu** [comment]
> KDL is good, particularly for underactuated arms. You could even balance orientation vs. position error. For further investigation, please prepare a zip comprising all relevant packages (URDF, SRDF/moveit_config, your source, exact commands to reproduce.)

Here they are:
[mtc.zip](https://github.com/ros-planning/moveit_task_constructor/files/14072100/mtc.zip)

`roslaunch rake_robotic_arm_moveit_config mtc_launch.launch`

Let me know if there is anything necessary to run it is missing.

**Comment by denizkitu** [comment]
Here they are:
[mtc.zip](https://github.com/ros-planning/moveit_task_constructor/files/14072122/mtc.zip)

You have to run: `roslaunch rake_robotic_arm_moveit_config mtc_launch.launch`

Let me know if anything necessary to run it is missing. Also keep in mind that the line `position_only_ik: true` is added to kinematics.yaml

**Comment by denizkitu** [comment]
> KDL is good, particularly for underactuated arms. You could even balance orientation vs. position error. For further investigation, please prepare a zip comprising all relevant packages (URDF, SRDF/moveit_config, your source, exact commands to reproduce.)

https://github.com/ros-planning/moveit_task_constructor/issues/526#issuecomment-1910307961

**Comment by denizkitu** [comment]
> KDL is good, particularly for underactuated arms. You could even balance orientation vs. position error. For further investigation, please prepare a zip comprising all relevant packages (URDF, SRDF/moveit_config, your source, exact commands to reproduce.)

Here they are:
[mtc.zip](https://github.com/ros-planning/moveit_task_constructor/files/14072128/mtc.zip)

You have to run: `roslaunch rake_robotic_arm_moveit_config mtc_launch.launch`

Let me know if anything necessary to run it is missing. Also keep in mind that the line `position_only_ik: true` is added to kinematics.yaml file

**Comment by rhaschke** [comment]
Thanks. Note, that it will take some time before I can have a deeper look into this.

**Comment by denizkitu** [comment]
> Thanks. Note, that it will take some time before I can have a deeper look into this.
Sure! Thanks in advance.

**Comment by rhaschke** [comment]
You have configured your KDL-based IK solver with `position_only_ik: true`. This means that orientation is ignored.
Note that the wrist joint position is always reached in your examples. ComputeIK first back-projects the Cartesian goal pose using the IK frame offset you defined, such that the goal is represented w.r.t. the eef link (probably `gripper_link`).
The IK solver then operates on this pose, which is always perfectly reached (in position only as you commanded).
However, as there is the frame offset and a _random_ orientation, the goal frame is offset along that random orientation.

I don't think you can achieve your grasping task with a 5-dof arm.
