### ISSUE TITLE
Long computation time in `ComputeIK` makes the task planning time very long

### ISSUE THREAD

**Issue by captain-yoshi** [ros-planning/moveit_task_constructor#533]
This issue might be related with the current limitations of the scheduler #312.

For my 2 cases I have a task which requires one ik solution.

### Trac-IK with `Speed` solver type (returns on the first successful ik)
Everything is good, the task is planned in 294 milliseconds.

![image](https://github.com/ros-planning/moveit_task_constructor/assets/32679594/5f8bdbab-b796-4bd5-8375-ee545ae25b56)

### Trac-IK with `Distance` solver type (returns best solution after a timeout)
Holy macaroni ! It takes 37 seconds for planning the task. It took 2.8 seconds for returning an IK solution, which is normal because it stops after the timeout. While the IK is different from the other case, I don't think it's the bottleneck here.

![image](https://github.com/ros-planning/moveit_task_constructor/assets/32679594/3064b51f-2f1e-4257-adb4-7241237513d2)

---

Is there a way to speed up the process ?

**Comment by captain-yoshi** [comment]
Pilz does not check collision when planning the path, so it is normally super fast (unless there is a bug).

I have managed to almost have the exact IK joint configuration as the one who gives 38 seconds to plan. Joint positions: (Left) Distance, (Right) Speed solve type.
<p align="middle">
<img src="https://github.com/ros-planning/moveit_task_constructor/assets/32679594/a3800a98-4c23-4258-8c04-2d1787df74b0" width="48%" />
  <img src="https://github.com/ros-planning/moveit_task_constructor/assets/32679594/1f1e880b-a293-4b9e-800d-c6904e6c7569" width="48%" />
  
</p>



### Trac-IK with `Distance` solver type
Same as before.
![image](https://github.com/ros-planning/moveit_task_constructor/assets/32679594/e0eb60b1-9c6a-43a6-a0ae-3e81c65ccace)


### Trac-IK with `Speed` solver type
With almost the exact IK cost and joint configuration. It takes 11 seconds but I have 8 seconds of trying to find 32 IK's and the rest is for planning the combinations. Which gives about 3 seconds to plan multiple sub-tasks.
![image](https://github.com/ros-planning/moveit_task_constructor/assets/32679594/86278463-84a3-4d44-b9f8-ebaad69be662)

---

As you can see, when the `compute_ik` stage does not return fast (Distance solve type) it takes 36 seconds to plan 1 trajectory. When the `compute_ik` stage returns fast (Speed solve type) it takes 3 seconds to plan multiple trajectories.

**Comment by captain-yoshi** [comment]
Oh well this one's on me...

Well if I set the IK to return after a timeout, this will also affect the other LIN Pilz planners of the same group because they rely on the IK solver. Mystery solved.

**Comment by rhaschke** [comment]
Knowing that you use the Pilz planner for subsequent stages, this would have been my next hint :wink:
Can we close this issue?
