### ISSUE TITLE
Store stages as std::shared_ptr

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit_task_constructor#74]
... instead of `std::unique_ptr`. The `MonitoringGenerator` needs to reference another stage, which is currently only possible via raw pointers. Using `std::shared_ptr` as  storage, MonitoringGenerators could use a `std::weak_ptr` to safely store the stage reference.

Also add a mechanism to retrieve child stages by name or index, possibly even recursively.

**Comment by v4hn** [comment]
basically a duplicate of #140
